feat: wip update to python 3.13

diff --git a/python/Dockerfile b/python/Dockerfile
--- a/python/Dockerfile
+++ b/python/Dockerfile
@@ -1,33 +1,23 @@
 # syntax=docker/dockerfile:1
-ARG PYTHON_VERSION=3.11
+# renovate: datasource=python-version depName=python packageName=python
+ARG PYTHON_VERSION=3.13.1
 ARG DEBIAN_VERSION=12
 
-FROM debian:$DEBIAN_VERSION AS builder
+FROM "debian:$DEBIAN_VERSION" AS builder
 
 ARG PYTHON_VERSION
 
 SHELL ["/bin/bash", "-c"]
 
+# ref: https://docs.docker.com/reference/dockerfile/#example-cache-apt-packages
 RUN set -eux; \
-    # Setup flags
-    # ref: https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/main/makepkg.conf
-    arch="$(dpkg --print-architecture)"; \
-    case "$arch" in \
-        # ref: https://github.com/aws/aws-graviton-getting-started/blob/main/c-c++.md
-        arm64) CFLAGS='-mcpu=neoverse-n1' ;; \
-        # ref: https://github.com/clearlinux-pkgs/gcc/blob/main/gcc.spec
-        amd64) CFLAGS='-march=westmere -mtune=sapphirerapids -fcf-protection' ;; \
-        *) echo >&2 "error: unsupported architecture: $arch" && exit 1 ;; \
-    esac; \
-    # ref: https://bugs.gentoo.org/700012
-    # also: dpkg-buildflags --get CFLAGS
-    export CFLAGS="$CFLAGS -O3 -pipe -fno-plt -fexceptions \
-                   -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
-                   -fstack-protector-strong -fstack-clash-protection"; \
-    export CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"; \
-    export LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,--strip-all'; \
-    export MAKEOPTS="-j$(cat /proc/cpuinfo | grep processor | wc -l)"; \
-    # Install dependencies
+    rm -f /etc/apt/apt.conf.d/docker-clean; \
+    echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
+
+RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
+    --mount=type=cache,target=/var/lib/apt,sharing=locked \
+    set -eux; \
+    # 1. install dependencies
     # ref: https://github.com/python/cpython/blob/main/.github/workflows/posix-deps-apt.sh
     apt update; \
     apt install -y build-essential \
@@ -41,14 +31,35 @@ RUN set -eux; \
                    libssl-dev \
                    libb2-dev \
                    # not essential
-                   libgdbm-dev \
                    libsqlite3-dev \
                    libncurses-dev \
-                   libreadline-dev; \
-    rm -rf /var/lib/apt/lists/*; \
+                   libreadline-dev;
+
+RUN set -eux; \
+    # 2. setup flags
+    # ref: https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/main/makepkg.conf
+    arch="$(dpkg --print-architecture)"; \
+    case "$arch" in \
+        # ref: https://github.com/aws/aws-graviton-getting-started/blob/main/c-c++.md
+        arm64) CFLAGS='-mcpu=neoverse-n1' ;; \
+        # ref: https://github.com/clearlinux-pkgs/gcc/blob/main/gcc.spec
+        amd64) CFLAGS='-march=westmere -mtune=sapphirerapids -fcf-protection' ;; \
+        *) echo >&2 "error: unsupported architecture: $arch" && exit 1 ;; \
+    esac; \
+    # ref: https://bugs.gentoo.org/700012
+    # also: dpkg-buildflags --get CFLAGS
+    export CFLAGS="$CFLAGS -O3 -pipe -fno-plt -fexceptions \
+                   -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
+                   -fstack-protector-strong \
+                   -fstack-clash-protection \
+                   -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer \
+                   -flto=auto"; \
+    export CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"; \
+    export LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,--strip-all'; \
+    export MAKEOPTS="-j$(cat /proc/cpuinfo | grep processor | wc -l)"; \
     mkdir /work; \
     pushd /work; \
-    # Build zlib (cloudflare fork)
+    # 3. build zlib (cloudflare fork)
     git clone --depth 1 https://github.com/cloudflare/zlib; \
     pushd zlib; \
     ./configure --static; \
@@ -58,21 +69,13 @@ RUN set -eux; \
     make "$MAKEOPTS"; \
     make test; \
     popd; \
-    # Build python
-    git clone --depth 1 --branch "$PYTHON_VERSION" https://github.com/python/cpython; \
+    # 4. build python
+    git clone --depth 1 --branch "v$PYTHON_VERSION" https://github.com/python/cpython; \
     pushd cpython; \
     # test modules as shared libraries
     sed -i '/^# Test modules/a \*shared\*' Modules/Setup.stdlib.in; \
-    # fully ported to PY_STDLIB_MOD in 3.12
-    # on 3.11, LIBFFI_LIBS, CURSES_LIBS, PANEL_LIBS, LIBREADLINE_LIBS are not yet available
-    # ref: https://github.com/python/cpython/issues/90005
-    sed -i 's/^#@MODULE__CTYPES_TRUE@\(.*\)/\1 @LIBFFI_LIBS@/' Modules/Setup.stdlib.in; \
-    sed -i 's/^#@MODULE__CURSES_TRUE@\(.*\)/\1 @CURSES_LIBS@/' Modules/Setup.stdlib.in; \
-    sed -i 's/^#@MODULE__CURSES_PANEL_TRUE@\(.*\)/\1 @PANEL_LIBS@/' Modules/Setup.stdlib.in; \
-    sed -i 's/^#@MODULE_READLINE_TRUE@\(.*\)/\1 @LIBREADLINE_LIBS@/' Modules/Setup.stdlib.in; \
     cat Modules/Setup.stdlib.in; \
     ln -svrf Modules/Setup.stdlib Modules/Setup.local; \
-    sed -i '/^ac_subst_vars=/a LIBFFI_LIBS\nCURSES_LIBS\nPANEL_LIBS\nLIBREADLINE_LIBS' configure; \
     ./configure --enable-option-checking=fatal \
                 --enable-optimizations \
                 --with-lto \
@@ -81,7 +84,6 @@ RUN set -eux; \
                 BZIP2_LIBS=-l:libbz2.a \
                 # follow pkg-config deps by hand
                 CURSES_LIBS='-l:libncursesw.a -l:libtinfo.a' \
-                GDBM_LIBS=-l:libgdbm.a \
                 LIBB2_LIBS=-l:libb2.a \
                 LIBFFI_LIBS=-l:libffi.a \
                 LIBLZMA_LIBS=-l:liblzma.a \
@@ -89,16 +91,13 @@ RUN set -eux; \
                 LIBSQLITE3_LIBS=-l:libsqlite3.a \
                 LIBUUID_LIBS=-l:libuuid.a \
                 PANEL_LIBS='-l:libpanelw.a -l:libncursesw.a -l:libtinfo.a' \
-                ZLIB_LIBS=../zlib/libz.a \
-                # do not link against libnsl/libcrypt (will be removed in 3.13)
-                py_cv_module_nis=n/a \
-                py_cv_module__crypt=n/a; \
+                ZLIB_LIBS=../zlib/libz.a; \
     make "$MAKEOPTS"; \
     make test; \
     make install DESTDIR=/rootfs; \
     popd; \
     popd; \
-    # Strip out unnecessary files
+    # 5. strip out unnecessary files
     # ref: https://github.com/docker-library/python/blob/master/Dockerfile-linux.template
     set +x; before="$(set +x; find /rootfs)"; set -x; \
     find /rootfs/usr/local -depth \
@@ -107,7 +106,7 @@ RUN set -eux; \
          -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name 'libpython*.a' \) \) \
         \) -exec rm -rv '{}' +; \
     find /rootfs/usr/local -depth -type d -name __pycache__ -delete; \
-    pyid="python$PYTHON_VERSION"; \
+    pyid="python${PYTHON_VERSION%.*}"; \
     pushd /rootfs/usr/local; \
     find . -maxdepth 1 ! -name bin ! -name lib ! -name . -exec rm -rv '{}' +; \
     # bin cleanup
@@ -123,14 +122,10 @@ RUN set -eux; \
     [ -z "$(ls lib-dynload | grep -v test | grep -v xxlimited)" ]; \
     # lib-dynload dir should exist to remove 'Could not find platform dependent libraries <exec_prefix>'
     rm -v lib-dynload/*; \
-    # follow Debian convention
+    # follow debian convention
     rm -rv config-* \
            # python3-venv
            ensurepip \
-           # python3-distutils (will be removed in 3.12)
-           distutils \
-           # python3-lib2to3
-           lib2to3 \
            # idle-python3
            idlelib \
            # python3-tk
@@ -140,13 +135,13 @@ RUN set -eux; \
     popd; \
     popd; \
     popd; \
-    # Print contents
+    # 6. print contents
     set +x; after="$(set +x; find /rootfs)"; set -x; \
     diff <(set +x; echo "$before") <(set +x; echo "$after") || true; \
     find /rootfs; \
     ldd -r /rootfs/usr/local/bin/python;
 
-FROM gcr.io/distroless/cc-debian$DEBIAN_VERSION AS latest
+FROM "gcr.io/distroless/cc-debian$DEBIAN_VERSION" AS latest
 
 ENV NVIDIA_VISIBLE_DEVICES=all
 ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
